### ISSUE TITLE
Prototype GUI

### ISSUE THREAD

**Issue by LoserAim** [LoserAim/Junior-Project-3d-printer-app#16]
This holds the prototype of the GUI. Please comment or add documents to showcase what the GUI should be.

**Comment by LoserAim** [comment]
[Uploading IMG-0550.JPG...]
[Uploading IMG-0552.JPG...]

**Comment by LoserAim** [comment]
![IMG-0550.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc6a7b71d741f0013de39af/125516c66e82c728ace21e0d46c1b9bd6ed2d6fcdfabf301b44fff9e2c4533317346f6297384ba79ec417e570e5b1aa941585916ada88f2baee72e6c981e5ab38532022d8c6853beb2901eb60bbb258f4f85b6bf8e4ec4ee3a24f5c6.JPG)

**Comment by LoserAim** [comment]
[Uploading IMG-0552.JPG...]

**Comment by BradBergstrom** [comment]
Needs a update/overhaul

**Comment by LoserAim** [comment]
![IMG-0552.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc6a7b71d741f0013de39af/125516c66e82c728ace21e0d46c1b9bd6ed2d6fcddabf301b44fff9e2c4533317346f6297384ba79ec417e570e5b1aa941585916ada88f2baee72e6c981e5ab38532022d8c6853beb2901dbf0bbb258f4f85b6bf8e44c5ed3526f5c6.JPG)

**Comment by LoserAim** [comment]
Internet Explorer

**Comment by LoserAim** [comment]
Main screen will have a hamburger Icon top Left to go to a naviagation drawer
The drawer will have a these options:
Admin Login
Options
Quit

**Comment by LoserAim** [comment]
https://cdn.discordapp.com/attachments/496863901305143296/504469077603909661/unknown.png
